export const ACCOUNT_LOGIN_ACTION_TYPE = 'ACCOUNT_LOGIN_ACTION_TYPE';
export const ACCOUNT_LOGOUT_ACTION_TYPE = 'ACCOUNT_LOGOUT_ACTION_TYPE';

export const TODO_ADD_ACTION = 'TODO_ADD_ACTION';
export const TODO_TOGGLE_ACTION = 'TODO_TOGGLE_ACTION';
export const TODO_SET_VISIBILITY_FILTER_ACTION = 'TODO_SET_VISIBILITY_FILTER_ACTION';